version: "2"
services:
  fed-notebook:
    image: fed-notebook_image
    restart: always
    container_name: fed-notebook_app
    build:
      context: ./
      dockerfile: Dockerfile-notebook

  fed-hub:
    image: fed-hub_image
    restart: always
    container_name: fed-hub_app
    build:
      context: ./
      dockerfile: Dockerfile-hub
    command: jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
    volumes:
      - ./envs/development/hub/etc/passwd:/etc/passwd:ro
      - ./envs/development/hub/etc/shadow:/etc/shadow:ro
      - ./envs/development/hub/etc/group:/etc/group:ro
      - ./envs/development/hub/etc/jupyterhub:/etc/jupyterhub:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    networks:
      - fed-net-hub
    environment:
      HOST_BASEDIR: ${PWD}
      BASE_URL: /fedbiomed/
      DOCKER_JUPYTERLAB_IMAGE: fed-notebook_image
      DOCKER_NETWORK_NAME: fedbiomed_fed-net-hub
      HUB_IP: fed-hub_app

      JUPYTERLAB_USER: root
      JUPYTERLAB_VOLUME_RO: /envs/development/notebook/start-notebook.d:/usr/local/bin/start-notebook.d
        /envs/development/notebook/before-notebook.d:/usr/local/bin/before-notebook.d
        /envs/development/notebook/data/samples:/home/samples
      JUPYTERLAB_VOLUME_RW: /envs/development/notebook/data/notebook:/home/notebook
      # This part didn't worked for fedbiomed jupyterhub, if it can work 
      # we can define env variable such as MQTT UPLOADS_URL etc. here. 
      JUPYTERLAB_ENVIRONMENT: NB_USER:fedclient
        NB_UID:998
        NB_GROUP:fedclient
        NB_GID:998
        CHOWN_HOME:yes
        CHOWN_HOME_OPTS:-R
        CHOWN_EXTRA:/home/fedclient/notebook
        CHOWN_EXTRA_OPTS:-R
        RESTARTABLE:yes

networks:
  fed-net-hub:
    driver: bridge
