version: "3.7"

services:
  #
  # restful http server component
  restful:
    container_name: fedbiomed-dev-restful
    build:
      context: ./restful/build_files
      args:
        - CONTAINER_UID
        - CONTAINER_GID
        - CONTAINER_USER
        - CONTAINER_GROUP
    image: fedbiomed/dev-restful
    #user: "${CONTAINER_UID:-root}:${CONTAINER_GID:-root}"
    environment:
      - PRODUCTION=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=santiago-smith.silva-rincon@inria.fr
      - DJANGO_SUPERUSER_PASSWORD=admin123
    ports:
      - "8844:8000"
    volumes:
      - ./restful/run_mounts/app:/app # django application
  #
  # mosquitto server component
  mqtt:
    container_name: fedbiomed-dev-mqtt
    image: eclipse-mosquitto
    # enable mqtt without authentication
    entrypoint: [ "/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf" ]

    ports:
      - "1883:1883"
      - "9001:9001"

  gui:
    container_name: fedbiomed-dev-gui
    build:
      context: ../../..
      dockerfile: envs/development/docker/gui/build_files/Dockerfile
    image: fedbiomed-dev/node-gui
    environment: 
      - DATA_HOST_PATH=${ROOT_DIR}
    volumes: 
      - ./gui/run_mounts:/app
      - ../../../etc:/fedbiomed/etc
      - ../../../var:/fedbiomed/var
      - ../../../data:/fedbiomed/data

    ports:
      - "5000:5000"