
name: Open a new Issue
description: For reporting a bug, proposing a new feature, enhancing an existing one, asking a question...
title: "[New issue]: "
labels: needs-triage
body:
  - type: textarea
    id: descr
    attributes:
      label: Dear user, welcome to the Fed-BioMed project ! We will get back to you as soon as possible.
      description: "*For developers, please tag your issue with the `candidate` label.*"
      placeholder: Your question, proposal, bug, ...
    validations:
      required: true