version: "3.7"
services:
  #
  # intermediate step : image for building wireguard for base image
  # we usually dont want to build or launch this service (only used for building "base")
  builder:
    container_name: fedbiomed-builder
    build:
      context: ./base/build_files
      target: builder
    image: fedbiomed/builder
    entrypoint: /bin/true
    # profiles will handle not-launched-by-default services when 
    # >=1.28 becomes common https://docs.docker.com/compose/profiles/
    # 
    # profiles:
    #  - debug # not started by `docker-compose up` except if `--profile debug`
  #
  # intermediate step : base image for building vpn, node and researcher containers
  # we usually dont want to launch this service (used for building other services)
  base:
    container_name: fedbiomed-base
    build:
      context: ./base/build_files
    image: fedbiomed/base
    entrypoint: /bin/true
    # profiles:
    #  - debug
  #
  # vpn server component
  vpnserver:
    container_name: fedbiomed-vpnserver
    build:
      context: ./vpnserver/build_files
      args:
        - CONTAINER_UID # build and use other account than "root"
        - CONTAINER_GID # build and use other group than "root"
    image: fedbiomed/vpnserver
    env_file:
      - ./vpnserver/run_mounts/config/config.env
    #environment:
    ## not needed, use image settings
    #  - CONTAINER_UID
    #  - CONTAINER_GID
    cap_add:
      - net_admin # needed to handle wireguard interface
      - sys_module # needed to remove wireguard kernel module
    devices:
      - /dev/net/tun # needed to handle wireguard interface
    volumes:
      - ./vpnserver/run_mounts/config:/config # contains VPN configurations
    ports:
      - 51820:51820/udp
  #
  # node component
  node:
    container_name: fedbiomed-node
    build:
      context: ../../..
      dockerfile: envs/vpn/docker/node/build_files/Dockerfile
      args:
        - CONTAINER_UID
        - CONTAINER_GID
    image: fedbiomed/node
    env_file:
      - ./node/run_mounts/config/config.env
    cap_add:
      - net_admin
      - sys_module
    devices:
      - /dev/net/tun
    volumes:
      - ./node/run_mounts/config:/config # contains VPN configurations
      - ./node/run_mounts/data:/data # datasets can be added here
  #
  # mqtt server component
  mosquitto:
    container_name: fedbiomed-mqtt-vpn
    build:
      context: ./mosquitto/build_files
    image: fedbiomed/mosquitto
    #image: eclipse-mosquitto
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf"]
    ports:
      - "1883:1883"
      - "9001:9001"


      