version: '3'

services:
  api:
    container_name: fedbiomed-dev-restful
    build: .
    command: sh -c "gunicorn -w 4 -b 0.0.0.0:8000 --log-level debug fedbiomed.wsgi"
    user: "${CONTAINER_UID:-root}:${CONTAINER_GID:-root}"
    environment:
      - FORCE_SCRIPT_NAME
      - PRODUCTION=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=dummy@gitlab.inria.fr
      - DJANGO_SUPERUSER_PASSWORD=admin123
    volumes:
      - .:/app
    ports:
      - "8844:8000"
  mqtt:
    container_name: fedbiomed-dev-mqtt
    #image: toke/mosquitto
    image: eclipse-mosquitto
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf"]
    ports:
      - "1883:1883"
      - "9001:9001"
