name: Fed-BioMed Build test
run-name: Fed-BioMed Build test
on: 
  push:
    branches: 
      - 'feature/github-self*'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - assigned 
      - ready-for-review

    branches:
      - master
      - develop

permissions:
  checks: write 

jobs:
  build-test:
    name: fedbiomed-ubuntu-22-04-unit-tests
    runs-on: [self-hosted, Linux, ubuntu-22-04]
    outputs:
      coverage: ${{ steps.filter.outputs.docs }}
    steps:
      
      - name: Checkout to commit
        uses: actions/checkout@v3

      - name: Run unit tests
        id: unit-test
        uses: ./.github/actions/unit-tests
        with:
          test-dir: test

      - name: Echo coverage
        run: |
          echo ${{steps.unit-test.outputs.coverage}}