name: Fed-BioMed Nightly Tests
run-name: Fed-BioMed Ubuntu-22-04 Nightly Tests
on:
  schedule:
    - cron: '0,5,10,15,20,25,30 15 * * *'


jobs: 
  build-test:
    name: Ubuntu 22.04 unit tests
    runs-on: [self-hosted, Linux, ubuntu-22-04]
    strategy:
      max-parallel: 4
      matrix:
        branch:
         - master
         - develop

    outputs:
      coverage: ${{ steps.unit-test.outputs.coverage }}
      master-coverage: ${{ steps.unit-test.outputs.master-coverage }}
      develop-coverage: ${{ steps.unit-test.outputs.develop-coverage }}

    steps:
      - name: Checkout to master
        uses: actions/checkout@v3
        with: 
          ref: ${{ matrix.branch }}

      - name: Run unit tests
        id: unit-test
        uses: ./.github/actions/unit-tests
        with:
          test-dir: tests

      - name: Test coverage
        run: |
          echo "${{ matrix.branch }}-coverage=${{steps.unit-test.outputs.coverage }}" >> $GITHUB_OUTPUT
  
  coverage-result: 
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: debug
        run: echo '${{ toJSON(needs.built-test.outputs) }}'


  integration-test: 
    name: Ubuntu 22.04 Integration tests
    runs-on: [self-hosted, Linux, ubuntu-22-04]
    strategy:
      max-parallel: 4
      matrix:
        branch:
         - master
         - develop
    steps:
      - name: Checkout to master
        uses: actions/checkout@v3
        with: 
          ref: ${{matrix.branch}}

      - name: Run MNIST Test - Master
        run: |
          source ~/.bashrc
          ./scripts/run_test_mnist data
