name: Fed-BioMed Nightly Tests
on:
  schedule:
    - cron: '30,35,40,45 14 * * *'


jobs: 
  build-test:
    name: Ubuntu 22.04 unit tests
    runs-on: [self-hosted, Linux, ubuntu-22-04]
    strategy:
      max-parallel: 4
      matrix:
        branch:
         - master
         - develop

    outputs:
      coverage: ${{ steps.unit-test.outputs.coverage }}

    steps:
      - name: Checkout to master
        uses: actions/checkout@v3
        with: 
          ref: ${{ matrix.branch }}

      - name: Run unit tests
        id: unit-test
        uses: ./.github/actions/unit-tests
        with:
          test-dir: tests

      - name: Test coverage
        run: |
          echo ${{steps.unit-test.outputs.coverage}}

  integration-test: 
    name: Ubuntu 22.04 Integration tests
    runs-on: [self-hosted, Linux, ubuntu-22-04]
    strategy:
      max-parallel: 4
      matrix:
        branch:
         - master
         - develop
    steps:
      - name: Checkout to master
        uses: actions/checkout@v3
        with: 
          ref: ${{matrix.branch}}

      - name: Run MNIST Test - Master
        run: |
          source ~/.bashrc
          ./scripts/run_test_mnist
