name: TEST
on:
  push:
    branches:
      - 'feature/764*'

jobs:
  build-doc:
    name: Test push
    environment: fedbiomed.github.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to commmit
        uses: actions/checkout@v3
      
      - name: Checkout to fedbiomed.github.io
        uses: actions/checkout@v3
        with:
          repository: fedbiomed/fedbiomed.github.io
          ssh-key: ${{ secrets.FEDBIOMED_GITHUB_IO_DEPLOY_KEY }}
          path: build-repo

      - name: git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<fedbiomed>"

      - name: Test push
        run: |
          cd build-repo
          echo "Test file" >> test.txt 
          git add .
          git commit -m "Testing push with deploy key" 
          git pull --no-edit --no-rebase  
          if [ ! git commit -a -m "Pulling recent changes" ]; then
            echo "o changes to commit"
          fi
          git push
          cd ../
